"""add email to renters

Revision ID: 0abb0dce9555
Revises: 5c7603b3ae64
Create Date: 2026-06-01 17:36:45.082675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abb0dce9555'
down_revision: Union[str, Sequence[str], None] = '5c7603b3ae64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renters', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renters', 'email')
    # ### end Alembic commands ###
